.\" Copyright (c) 2012-2016, Lester Hedges <lester.hedges+latuxit@gmail.com>
.\"
.\" %%%LICENSE_START(GPLv2+_DOC_FULL)
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, see
.\" <http://www.gnu.org/licenses/>.
.\" %%%LICENSE_END
.if !\n(.g \{\
.   if !\w|\*(lq| \{\
.       ds lq ``
.       if \w'\(lq' .ds lq "\(lq
.   \}
.   if !\w|\*(rq| \{\
.       ds rq ''
.       if \w'\(rq' .ds rq "\(rq
.   \}
.\}
.de Id
.ds Dt \\$4
..
.Id $Id: latuxit.1,v 1.00 2016/06/03 10:13:32 lester Exp $
.TH LATUXIT 1 \*(Dt "Lester Hedges"
.SH NAME
latuxit \- create a cropped LaTeX equation in PDF and PostScript format.
.SH SYNOPSIS
.B latuxit
.RI [ options ]
.br
.B latuxit
.RI [ options ]
.RI [ IMAGE ]
.br
.B latuxit
.RI [ IMAGE ]
.P
.B echo
.RI \fI"equation\fI"
|
.B latuxit
.RI [ options ]
.br
.B cat
.RI [ FILE ]
|
.B latuxit
.RI [ options ]
.br
.B latuxit
<
.RI [ FILE ]
.RI [ options ]
.SH DESCRIPTION
.PP
.B latuxit
is a command-line Linux clone of the excellent Mac OS X program
.B LaTeXiT (http://pierre.chachatelier.fr/latexit)
.PP
.B latuxit
creates cropped
.B PDF
and
.B PostScript
images of
.B LaTeX
typeset equations processed by the
.B pdflatex
utility.
.B latuxit
has full RGB color support and also accepts any of the 68 standard colors known
to
.BR dvips .
Equations can be processed using several of the standard
.B amsmath
equation environments, and using custom
.B LaTeX
pre- and post-amble files.
Like
.BR LaTeXiT ,
.B latuxit
has reverse editing capability, i.e. one can edit an existing equation by
invoking
.B latuxit
on an image that was generated by
.BR latuxit .
Due to its command-line nature,
.B latuxit
provides a handy way of processing many equations from a batch script.
.PP
.B latuxit
works by hashing each equation string and building a library of equations in
.IR ~/.latuxit/library/ .
Metadata written to the output
.B PDF
and
.B PostScript
images allows
.B latuxit
to match an image to an equation in the library. While it is possible to
directly embed equations into the output images, inconsistencies in equation
formatting (particularly for long, multi-line equations) makes it difficult to
parse the metadata in a well defined way. Unfortuntely this means that one can
no longer edit an image if the equation library is deleted or corrupt. In
addition, images are not portable between different machines unless the library
is also transferred.
.PP
Due to the limited range of font sizes supported by LaTeX,
.B latuxit
uses the default size of 10pt. Since equations are output as vector images it
is trivial to rescale them afterwards.
.SH OPTIONS
.B
latuxit
supports the following short- and long-form command-line options. Invoking
.B latuxit
when no equation has been passed using the command-line option or via stdin
will open the editor defined by the
.B LATUXIT_EDITOR
environment variable. The user can then type an equation and
.B latuxit
will proceed as normal once the file has been saved and closed.
.TP
.BI \-e " EQUATION" "\fR,\fP \-\^\-equation "EQUATION
.I EQUATION
in LaTeX markup. No $ symbols are needed. The
.I EQUATION
should be surrounded by single quotation marks, i.e. '\fIEQUATION\fP'\fR, to
ensure that it is parsed correctly (strong quoting). When the equation starts
with a minus sign make sure the character is enclosed in curly braces,
i.e. '\fI{-}...\fP'\fR , so that it isn't mistaken as an identifier for a
command-line argument. Alternatively, simply insert a blank space at the start
of the equation. This will be ignored by LaTeX when the equation is typset.
If no
.I EQUATION
is passed on the command-line or from stdin then
.B latuxit
will open the
.I EQUATION
editor defined by the
.B LATUXIT_EDITOR
environment variable. If
.B pdflatex
fails to process an
.I EQUATION
then the user will be given the opportunity to edit it again in order to
correct any mistakes.
.TP
.BI \-c " COLOR" "\fR,\fP \-\^\-color "COLOR
Where
.I COLOR
is one of the 68 standard colors defined in
.IR ~/.latuxit/latuxit.colors ,
or, alternatively, a
.I COLOR
in {R,G,B} format, where R,G,B=[0\-1.0], or [0\-255]. RGB colors should be
surrounded by single quotation marks, i.e. '\fI{R,G,B}\fP'\fR, to ensure
they are parsed correctly. Also make sure that there aren't any blank spaces
on either side of any of the RGB values.
.TP
.BI \-o " FILE_PREFIX" "\fR,\fP \-\^\-output "FILE_PREFIX
.I FILE_PREFIX
is a prefix used for all output images, e.g
.IR FILE_PREFIX .pdf.
The default is
.BR latuxit .
.TP
.BR \-d ", " \-\^\-displaymath
Sets the equation environment to
.BR displaymath .
This is the default environment. When setting an environment from the
command-line the final option will take precedence. The command-line
environment also takes precedence when processing an equation in hash
mode, or when reprocessing and existing
.B latuxit
image.
.TP
.BR \-a ", " \-\^\-align
Sets the equation environment to
.BR align .
.TP
.BR \-g ", " \-\^\-gather
Sets the equation environment to
.BR gather .
.TP
.BR \-l ", " \-\^\-list
Lists all equations in the library along with their hash.
.TP
.BI \-s " EQUATION" "\fR,\fP \-\^\-search "EQUATION
Searches the equation library for all partial matches of
.IR EQUATION .
The matches are output along with the corresponding hash.
.TP
.BI \-m " HASH" "\fR,\fP \-\^\-md5 "HASH
Run
.B latuxit
in "hash" mode. The
.I HASH
string is matched against equations in the library. It should be long enough to
ensure a unique match. Once a match is found,
.B latuxit
will open the equation for editing with
.BR LATUXIT_EDITOR .
Hashes are generated using the
.B md5sum
algorithm. A single letter prefix is added to specify the equation environment
that was used to process the equation.
.TP
.BR \-b ", " \-\^\-batch
Run
.B latuxit
in "batch" mode. In batch mode
.B latuxit
will no longer ask the user to edit any failed equations. This is useful when
processing a large number of equations using a batch script, e.g. when the user
doesn't want to edit many potentially incorrect equations by hand, or deal with
memory issues by opening many instanaces of the
.BR LATUXIT_EDITOR .
Any failed equations will be reported to
.B stdout
along with the
.B [FAILED]
prefix.
.
.TP
.BR \-p ", " \-\^\-purge
Purge the equation library.
.TP
.BI \-pre " PREAMBLE" "\fR,\fP \-\^\-preamble "PREAMBLE
Load a custom LaTeX preamble file. The
.I PREAMBLE
should be an appropriately formatted
.B tex
file.
.TP
.BI \-post " POSTAMBLE" "\fR,\fP \-\^\-postamble "POSTAMBLE
Load a custom LaTeX postamble file. The
.I POSTAMBLE
should be an appropriately formatted
.B tex
file.
.TP
.BR \-h ", " \-\^\-help
Get help (loads the man page).
.
.SH FILES
.TP
.B image
Running
.B latuxit
on an
.I IMAGE
that was previously created with
.B latuxit
will search the file for metadata and open the corresponding equation from the
library in the editor defined by the
.I LATUXIT_EDITOR
environment variable (see
.B ENVIRONMENT VARIABLES
section). This allows the user to modify an existing
.B latuxit
image. The image and equation are overwritten unless a different
.I FILE_PREFIX
is specified.
.SH "ENVIRONMENT VARIABLES"
.B latuxit's
behavior is affected by the following environment variables. These
can be sourced from
.I ~/.latuxitrc
or
.IR ~/.latuxit/latuxitrc .
.TP
.B LATUXIT_EDITOR
This variable specifies the editor to be used for typing equations. The default
option is
.BR vim .
.TP
.B LATUXIT_COLOR
The
.I COLOR
of the equation. The default is
.BR Black ,
but the command-line option
.B \-c
will take precedence.
.TP
.B LATUXIT_LIBRARY_SIZE
The size of the
.B latuxit
.I EQUATION
library. The default is 1000.
.TP
.B LATUXIT_POSTSCRIPT
Whether to also save a PostScript copy of the output PDF. The default is
.BR true .
.TP
.B LATUXIT_PURGE_CONFIRMATION
Whether to ask for confirmation before purging the equation library. The default
is
.BR true .
.TP
.B LATUXIT_PREAMBLE
The default
.B LaTeX
preamble,
.BR ~/.latuxit/preamble.tex .
.TP
.B LATUXIT_POSTAMBLE
The default
.B LaTeX
postamble,
.BR ~/.latuxit/postamble.tex .
.SH CREDITS
.PP
.BR LaTeXiT ,
for the inspiration
.BR (http://pierre.chachatelier.fr/latexit) .
.PP
Ideas taken from Giovanni Lanzani
.BR (www.lanzani.nl/latexit.html) .
.SH BUGS
.PP
Email bug reports to
.BR lester.hedges+latuxit@gmail.com .
